# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='EPAAA')),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
