# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(default='Nada', max_length=90),
        ),
        migrations.AddField(
            model_name='alumno',
            name='promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(default=0),
        ),
    ]
