# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auto_20160113_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=90),
        ),
    ]
