# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_auto_20160113_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='no_control',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
