# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auto_20160114_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='semestre',
        ),
    ]
