# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_auto_20160114_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
