INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (1, 'Ing. Sistemas Computacionales', 1);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (2, 'Ing. Industrial', 2);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (3, 'Ing. Civil', 3);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (4, 'Ing. Quimica', 4);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (5, 'Ing. Petrolera', 5);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (6, 'Ing. Ambiental', 6);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (7, 'Ing. Bioquimica', 7);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (8, 'Ing. Informatica', 8);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (9, 'Lic. en Administracion', 9);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (10, 'Ing. Gestion Empresarial', 10);
INSERT INTO "cuentas_carrera" ("id", "carrera", "ROWID") VALUES (11, 'Ing. en Tecnologias de la Informacion y Comunicaciones', 11);
